### ISSUE TITLE
Fails when relation is not present: "undefined method `id' for nil:NilClass"

### ISSUE THREAD

**Issue by tscolari** [Netflix/fast_jsonapi#124]
It seems that https://github.com/Netflix/fast_jsonapi/blob/7e59446717b0018f46c0d73a59e915acc15930b6/lib/extensions/has_one.rb#L12 gives you an error if the relation is not present (e.g. `relation_id == nil`) with 

```
undefined method `id' for nil:NilClass
```

if you explicitly call that `relation_id` method from your code.

in this case `reader` is nil.
I'm not sure if I'm doing something wrong, since I couldn't find anyone else complaining about this, but if this is in fact an issue I would be more than happy to PR a fix.

Thanks,

**Comment by tscolari** [comment]
I just realised the fix pointed in https://github.com/Netflix/fast_jsonapi/issues/121 will fix this.
Sorry!

**Comment by mauricio3d** [comment]
Don't worry everything is gonna be right

El 15 mar. 2018 9:04 a. m., "Tiago Scolari" <notifications@github.com>
escribió:

I just realised the fix pointed in #121
<https://github.com/Netflix/fast_jsonapi/issues/121> will fix this.
Sorry!

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Netflix/fast_jsonapi/issues/124#issuecomment-373386670>,
or mute the thread

**Comment by shishirmk** [comment]
@tscolari can you help test #121 so that i can merge it in?

**Comment by tscolari** [comment]
@shishirmk -> replied you in #121 ^^
