### ISSUE TITLE
Error with namespaced relations with inclusions

### ISSUE THREAD

**Issue by AtomGrafiks** [Netflix/fast_jsonapi#16]
An error is perform when includes an associations has_one 

```ruby
class Cluster::LocationSerializer 
  include FastJsonapi::ObjectSerializer
  attributes :begin_at, :end_at

  has_one :workspace, serializer: Cluster::WorkspaceSerializer
  has_one :user, serializer: Cluster::UserSerializer
end
```

```ruby
class Cluster::UserSerializer 
  include FastJsonapi::ObjectSerializer
  attributes :uid, :login, :nickname, :avatar_url
end
```

```ruby
class Cluster::WorkspaceSerializer 
  include FastJsonapi::ObjectSerializer
  attributes :identifier, :campus_id
end
```

call: 
```ruby
active_locations = Location.active.includes(:workspace, :user).references(:workspace, :user)
Cluster::LocationSerializer.new(active_locations, include: [:workspace, :user]).serializable_hash
```

Error : 
```
NameError - uninitialized constant Cluster::Cluster
```

**Comment by grossadamm** [comment]
Interesting.. I'd like to build a test to replicate this failure so I can verify it's truly resolved.

**Comment by sriniwasgr** [comment]
@AtomGrafiks i believe you have a typo in the Location Serializer. The optional key 'serializer' expects a symbol and by convention assumes all serializers are in the same namespace.

`class Cluster::LocationSerializer 
  include FastJsonapi::ObjectSerializer
  attributes :begin_at, :end_at

  has_one :workspace, serializer: :workspace
  has_one :user, serializer: user
end`

In your specific case, you dont even have to provide the key 'serializer' since your relationship name and serializer name are same.

`has_one :workspace`

**Comment by AtomGrafiks** [comment]
Ah, interesting, thanks ;)
