### ISSUE TITLE
Customize the root key after serialization

### ISSUE THREAD

**Issue by CoSNaYe** [Netflix/fast_jsonapi#289]
Hi, thanks for building this fast serializer. I'm migrating from `active_model_serializers` to `fast_jsonapi`. However, there's a difference between these two gems: the response from `active_model_serializers` is automatically wrapped by `model name`(e.g 'product'), but `fast_jsonapi` is always `data`.

Given that I already have a running service and I don't want to change its output for clients, could we have a way to modify the key?

example:
```ruby
class ProductSerializer
  include FastJsonapi::ObjectSerializer
  set_type :product

  attributes :name, :description
end

class Product
  include Mongoid::Document

  field :name, type: String
  field :description, type: String
end
```

Here's the output:
```ruby
product = Product.create({ name: 'a name', description: 'a product' })
ProductSerializer.new(product).serialized_json 
# output: { data: { ..... } }
# i wish we can customize it to be { product: { ... } }
```

Thanks.

**Comment by manojmj92** [comment]
@CoSNaYe - If I'm not wrong, JSON API spec mandates that the root element can only be called "data" and not something else:

Reference - http://jsonapi.org/format/#document-top-level

Are you currently using AMS with JSON API adapter? Can you please share the syntax by which you are able to customise the root element from "data" to "product" in AMS?

**Comment by manojmj92** [comment]
Hey @CoSNaYe!

Thanks for getting back with the data.

Correct me if I'm wrong, but I strongly feel that you might have mistaken "JSON API" with "JSON API Spec".

Because, you'd have to use 
`ActiveModelSerializers.config.adapter = :json_api` and not `ActiveModelSerializers.config.adapter = :json` for JSON API adapter to work.(https://stackoverflow.com/questions/33620859/changing-active-model-serializers-default-adapter)

So, my assumption is that what you currently have is just normal, simple JSON adapter, which is the default, and that is why the root elements are named after your model.

JSON API SPEC is a set of 'specifications' to standardise JSON responses, and from the code examples you have shared, it does not look like you are using the `JSON API SPEC`, rather you just have a simple 'JSON' endpoint. (http://jsonapi.org/)

This gem is specifically aimed at improving the speed of APIs that use the "JSON API SPEC" and is not aimed at normal JSON APIs, so your use case is not a valid use case right now.

Happy to explain further in case you have any questions :)

**Comment by CoSNaYe** [comment]
Hmmm... yes, you are right. AMS provides both `:json` and `:json_api` adaptor, and I should use `:json_api` in the beginning. 
https://github.com/rails-api/active_model_serializers/blob/v0.10.6/docs/general/adapters.md

And I agree that it's better I correct my codes to comply with the best practice.
Thanks.

**Comment by manojmj92** [comment]
@CoSNaYe happy to help! :)
Moving to `json_api` to just `json` will have breaking changes, so please do plan and test accordingly :)
