### ISSUE TITLE
Size attribute on object causes problems

### ISSUE THREAD

**Issue by blim8183** [Netflix/fast_jsonapi#291]
An object that I'm trying to serialize has an attribute called `size`. This is causing the error `undefined method 'each'`.

I'm assuming this is related to https://github.com/Netflix/fast_jsonapi/pull/234 which is checking for the existence of a method called `size` to determine whether the object is a collection.

**Comment by manojmj92** [comment]
Hey @blim8183,

Your analysis is correct. It is definitely due to the code in #234.
One quick way for you to solve this is to force `is_collection` to be false, so like,

```ruby
options = {}
options[:is_collection] = false
hash = YourSerializer.new(your_record, options).serializable_hash
```
This should work for you. Your case is really an edge case, and the ability to force `is_collection` was added especially to counter such kind of cases. Let me know if it works! :)

**Comment by manojmj92** [comment]
@blim8183 can you close this if the above response solved your problem?

**Comment by sgaxr** [comment]
@manojmj92 What do you think about adding a note about this in the readme? I've run into this a few times now (I work with a lot of file meta data). I feel like size, though not super common, is common enough to warrant a footnote at least.
