### ISSUE TITLE
serializable_hash vs serializable_json when rendering json

### ISSUE THREAD

**Issue by kapso** [Netflix/fast_jsonapi#392]
Whats the recommended way of using the serializer when rendering json in a controller? Is one better than the other?

```ruby
class PostsController < ApplicationController
  def index
    posts = Post.joins(:comments)

    render json: PostSerializer.new(posts).serialized_json
    render json: PostSerializer.new(posts).serializable_hash # OR
    render json: PostSerializer.new(posts) # OR
  end
end
```

**Comment by kapso** [comment]
Looks like all 3 produce the same output, but `.serialized_json` is the fastest. So closing this.

**Comment by Autumn-Martin** [comment]
This is a good question. I was discussing this with my mentee & came up with some additional thoughts on it for different use cases. 

When rendering json,`serializable_json` and  `serialized_hash` do _appear_ to have the same output on an api endpoint. And importantly, the 3rd option where neither serialize method is called(`json: PostSerializer.new(posts)`) just returns the **unserialized** PostSerializer object. Otherwise, the main difference is the class of the data that's being returned and how we can interact with it.
<img width="829" alt="Screen Shot of different classes" src="https://user-images.githubusercontent.com/36902512/87256635-a651df80-c451-11ea-8f78-c899d1c9673c.png">

`serialized_json` sends back a JSON string object. We'll need to parse it to retrieve the data we're looking for. 
<img width="829" alt="Screen Shot of serialized_json response" src="https://user-images.githubusercontent.com/36902512/87256522-b1f0d680-c450-11ea-998c-ec3abdab3b8c.png">
<img width="829" alt="Screen Shot of parsed serialized_json response" src="https://user-images.githubusercontent.com/36902512/87256526-b6b58a80-c450-11ea-9bdd-9df58e878d87.png">

Or, we could use `serializable_hash`. This returns a Hash object that we can retrieve data from right away.
<img width="829" alt="Screen Shot of serializable_hash response" src="https://user-images.githubusercontent.com/36902512/87256500-7fdf7480-c450-11ea-8457-22ca64811888.png">

For data that we're going to use internally on our views, `serializable_hash` might be best. For data that we're serving up in an api endpoint that returns JSON, might as well use `serialized_json`.
